import type { Account } from "@/features/accounts/accounts.types";

export const mockAccounts: Account[] = [
  {
    id: "ACC-001",
    accountType: "Broker Partner",
    accountName: "Project 1 Finance",
    billingState: "SA",
    ownerFirstName: "AFOS",
    createdDate: "14/12/2021, 2:55 pm",
    lastModifiedDate: "02/04/2026, 9:16 am",
    status: "active",
  },
  {
    id: "ACC-002",
    accountType: "Broker Partner",
    accountName: "Savvy",
    billingState: "SA",
    ownerFirstName: "AFOS",
    createdDate: "16/09/2021, 5:27 pm",
    lastModifiedDate: "07/07/2026, 2:39 pm",
    status: "active",
  },
  {
    id: "ACC-003",
    accountType: "Broker Partner",
    accountName: "Demo Loans",
    billingState: "SA",
    ownerFirstName: "AFOS",
    createdDate: "18/06/2025, 12:13 pm",
    lastModifiedDate: "15/09/2025, 11:42 am",
    status: "active",
  },
  {
    id: "ACC-004",
    accountType: "Person Account",
    accountName: "Happy Lora",
    mobile: "0415912941",
    email: "happy@example.com",
    ownerFirstName: "John",
    ownerLastName: "Doe",
    createdDate: "20/09/2021, 12:00 pm",
    lastModifiedDate: "15/05/2023, 4:15 pm",
    status: "active",
  },
  {
    id: "ACC-005",
    accountType: "Person Account",
    accountName: "Bruce Banner",
    mobile: "0400100100",
    email: "bruce@example.com",
    ownerFirstName: "System",
    ownerLastName: "Generated",
    createdDate: "20/09/2021, 12:52 pm",
    lastModifiedDate: "20/09/2021, 1:08 pm",
    status: "inactive",
  },
];